import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const exportPDF = (title, columns, rows) => {

  const doc = new jsPDF();

  // ==========================
  // College Name
  // ==========================

  doc.setFontSize(20);

  doc.setTextColor(13, 71, 161);

  doc.text(
    "Exam Seating Arrangement System",
    14,
    18
  );

  // ==========================
  // Report Title
  // ==========================

  doc.setFontSize(15);

  doc.setTextColor(0, 0, 0);

  doc.text(title, 14, 30);

  // ==========================
  // Generated Date
  // ==========================

  doc.setFontSize(10);

  doc.text(
    `Generated On : ${new Date().toLocaleString()}`,
    14,
    38
  );

  // ==========================
  // Table
  // ==========================

  autoTable(doc, {

    head: [columns],

    body: rows,

    startY: 45,

    theme: "grid",

    headStyles: {

      fillColor: [13, 71, 161],

      textColor: 255,

      fontSize: 11,

    },

    styles: {

      fontSize: 10,

      cellPadding: 3,

    },

    alternateRowStyles: {

      fillColor: [245, 245, 245],

    },

  });

  // ==========================
  // Footer
  // ==========================

  const pageHeight = doc.internal.pageSize.height;

  doc.setFontSize(10);

  doc.text(

    "Generated by Exam Seating Arrangement System",

    14,

    pageHeight - 10

  );

  doc.save(`${title}.pdf`);

};

export default exportPDF;